version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  deploy_fargate:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: arm.large # Resource Class(ARM VM)
      image: ubuntu-2004:2022.04.1
    steps:
      - checkout
      - aws-ecr/build-and-push-image: # AWS ECR Orb
          assume-web-identity: true
          new-profile-name: ${AWS_ROLE_ARN}
          platform: linux/arm64
          repo: tadashi-graviton-fargate-demo
          tag: '${CIRCLE_SHA1}'

workflows:
  test_and_deploy: 
    jobs:
      - deploy_fargate:
          filters:
            branches:
              only:
                - main
          context:
            - aws-oidc-fargate
