version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  deploy_fargate:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: arm.large # Resource Class(ARM VM)
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
      # - aws-ecr/build-and-push-image: # AWS ECR Orb
      #     assume-web-identity: true
      #     new-profile-name: new-profile
      #     role-arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
      #     platform: linux/arm64
      #     repo: tadashi-fargate-demo
      #     tag: '${CIRCLE_SHA1}'

workflows:
  test_and_deploy: 
    jobs:
      - deploy_fargate:
          filters:
            branches:
              only:
                - main
          context:
            - aws-oidc-fargate
